const expenditureData = [
  {
    iconUrl: "box-tick.png",
    grapghUrl: "graph-up.png",
    chartUrl: "trending-up.png",
    description: "Total Order",
    cost: 350,
    bgColor: "green",
  },
  {
    iconUrl: "3d-rotate.png",
    grapghUrl: "graph-down.png",
    chartUrl: "downward.png",
    description: "Total Refund",
    cost: 270,
    bgColor: "red",
  },
  {
    iconUrl: "shopping-cart.png",
    grapghUrl: "graph-down.png",
    chartUrl: "downward.png",
    description: "Average Sales",
    cost: 1567,
    bgColor: "red",
  },
  {
    iconUrl: "coin.png",
    grapghUrl: "graph-up.png",
    chartUrl: "trending-up.png",
    description: "Total Income",
    cost: "$350.00",
    bgColor: "green",
  },
];

const userTransactionData = [
  {
    aviUrl: "https://i.pravatar.cc/150?img=47",
    itemUrl: "pizza.jpg",
    quantity: 1,
    deliveryType: "home-delivery",
    userName: "Sarah Banks",
    amount: "$40,000",
    status: "Paid",
    item: "pepperoni pizza",
    totalExpense: "$12",
  },
  {
    aviUrl: "https://i.pravatar.cc/150?img=60",
    itemUrl: "coffee.jpg",
    quantity: 2,
    deliveryType: "pick-up",
    userName: "Josh Avril",
    amount: "$70,000",
    status: "Refund",
    item: "starbucks coffee",
    totalExpense: "$13.98",
  },
  {
    aviUrl: "https://i.pravatar.cc/150?img=48",
    userName: "Rebbeca Hathaway",
    itemUrl: "ps5.jpg",
    quantity: 1,
    deliveryType: "home-delivery",
    amount: "$110,000",
    status: "Paid",
    item: "playStation 5",
    totalExpense: "$495.34",
  },
  {
    aviUrl: "https://i.pravatar.cc/150?img=12",
    itemUrl: "pixel.jpg",
    quantity: 1,
    deliveryType: "pick-up",
    userName: "Dave Macron",
    amount: "$75,000",
    status: "Refund",
    item: "google pixel 7pro",
    totalExpense: "$699",
  },
  {
    aviUrl: "https://i.pravatar.cc/150?img=41",
    itemUrl: "macbook.jpg",
    quantity: 1,
    deliveryType: "pick-up",
    userName: "Cathlyn Campbell",
    amount: "609,000",
    status: "Paid",
    item: "Macbook Pro",
    totalExpense: "$780",
  },
];

const platforms = [
  {
    title: "Book Bazaar",
    price: "$2,500,000",
    rate: "+15%",
    level: "54%",
    color: "purple",
  },
  {
    title: "Artisan Aisle",
    price: "$1,800,000",
    rate: "+10%",
    level: "42%",
    color: "blue",
  },
  {
    title: "Toy Troop",
    price: "$1,200,000",
    rate: "+8%",
    level: "18%",
    color: "yellow",
  },
  {
    title: "XStore",
    price: "$1,000,000",
    rate: "+6.5%",
    level: "29%",
    color: "red-bar",
  },
];

export { expenditureData, userTransactionData, platforms };
